### ISSUE TITLE
Inventory Tracker - Duplicating Last Inventory Item

### ISSUE THREAD

**Issue by chrisbirie** [BaconCatBug/FFRK-Drop-Tracker#4]
I exported my inventory and it appears that the last item is duplicated. It is a Tenebraen Emblem (XV). It has two but I only have one in my inventory. I noticed it yesterday as well with a different item, but it was still Hero Equipment.

**Comment by chrisbirie** [comment]
https://pastebin.com/c6YuML0Q

Pastebin of my file

**Comment by BaconCatBug** [comment]
Thank you for catching that, I had a misindented else clause. This should be fixed now!
