### ISSUE TITLE
export missing soulbreaks

### ISSUE THREAD

**Issue by Le-Lucien** [BaconCatBug/FFRK-Drop-Tracker#5]
Hello,

Not sure if it's a problem with my setup but some soulbreaks aren't showing in the 3-FFRK-Soul-Breaks.txt. For example, when I export them with RKSquared, I'm getting 1202 results while with the the drop tracker, I'm getting 1028. I was using the default settings, only set the soul_break_export_level=1. I get a bit more enabling the crappy SB but I'm only getting up to 1043.

You can see the differences in this [file](https://docs.google.com/spreadsheets/d/1SJCMTPIHTJBZ9Z21ufUsbx_rsONJ1JwiPu4DTbFMeEM/edit?usp=sharing).

PS : there's also a typo in the Delete Inventory Export txts.bat, deleting the 3-FFRK-Soul_Breaks.txt and 7-FFRK-Legend_Materia.txt instead of 3-FFRK-Soul-Breaks.txt and 7-FFRK-Legend-Materia.txt

**Comment by BaconCatBug** [comment]
The default settings only export "Unique" tier and above (so no Defaultt level), and ignores the unique soulbreaks the core characters have. Can you give me a specific example of a soul break you own that isn't being exported by my scripts?

I'll fix the typo now in the delete script.

**Comment by Le-Lucien** [comment]
Thanks for the fast reply ! There's a few examples :
22590004	Matoya	Crystal Power	USB																				
22590005	Matoya	Witch's Awakening	AASB																				
22590006	Matoya	Crystal Burst	AOSB																				
20100007	Terra	Scorching Flames	OSB																					
20100008	Terra	Omen	USB1																						
20100011	Terra	Esper Flame	Glint1																					
20100012	Terra	Magitek Inferno	BUSB																					
20100013	Terra	Chaotic Inferno	AASB1																					
20100015	Terra	Riot Wind	AOSB2																						
20100016	Terra	Tornado Combo	USB3																					
20100018	Terra	Violent Sword	AASB2																					
20100021	Terra	Illusory Flame	Glint+1																				
20100024	Terra	Reviving Wind	Glint+2																				
20100034	Terra	Cross Meltdown	AASB3
20200008	Lenna	Moogle Boost	USB1																					
20200010	Lenna	Tycoon Princess	USB2																					
20200011	Lenna	Essence of Water	USB3																					
20200015	Lenna	Tycoon's Protection	Glint+1																			
20200017	Lenna	Princesses' Prayer	BUSB
20230003	Tifa	Waterkick	SB																						
20230004	Tifa	Burning Arrow	SB																					
20230007	Tifa	Meteor Strike	OSB																					
20230008	Tifa	Meteodrive	USB1																						
20230009	Tifa	Rolling Blaze	BSB2																					
20230010	Tifa	Platinum Strike	AOSB																					
20230013	Tifa	Meteor Arts	AASB1																						
20230016	Tifa	Eruption Garb	Glint+1																				
20230019	Tifa	Limit Combo	SASB2

In the [google doc I posted](https://docs.google.com/spreadsheets/d/1SJCMTPIHTJBZ9Z21ufUsbx_rsONJ1JwiPu4DTbFMeEM/edit?usp=sharing), they can be identified with the large green chunks in the 3rd tab. Seems it's affecting specific characters :
Alma, Alphinaud, Ashe, Balthier, Barret, Basch, Caith Sith, Cater, Ceodore, Cid Raines, Deuce, Dorgann and so on.

The only change I made when exporting was changing the export level to 1, instead of the default 2. They were already missing with the default settings.

**Comment by BaconCatBug** [comment]
Ok I think I know what's happened, the soul break json is split up and I think the maitinance changed how it's processed. I'll have to look into this tonight after work.

**Comment by Le-Lucien** [comment]
Thanks for your time ! :)

**Comment by BaconCatBug** [comment]
So, the game splits the json file where soul breaks are contained into 3. It used to be the case you'd always get part 0, 1, and 2 in that order, but for some reason the game is now giving part 1 first which messes things up. My fault for assuming they would always be in order. I'll implement a fix tonight.

**Comment by Le-Lucien** [comment]
That explains everything. Thanks for the explanation. :)

**Comment by BaconCatBug** [comment]
This should be resolved now with 1.03

**Comment by Le-Lucien** [comment]
Seems working fine now. Thanks again !
